### ISSUE TITLE
bash dependency

### ISSUE THREAD

**Issue by thesourcerer8** [efabless/openlane#104]
At least one of the scripts of openlane is relying on features of /bin/bash, but it actually uses #!/bin/sh  which is a symlink to /bin/dash on Ubuntu systems, which makes this function fail and error:
/bin/sh: 1: [[: not found

I would suggest to change all scripts from /bin/sh to /bin/bash to fix this.

**Comment by smunaut** [comment]
FYI That's been fixed in a branch already.

**Comment by agorararmard** [comment]
@thesourcerer8: I believe this is a duplicate issue for #82. Am I correct?

**Comment by smunaut** [comment]
https://github.com/efabless/caravel/commit/4666810f4506809d4f3fb1aaaa57d96edfaef385

**Comment by thesourcerer8** [comment]
No, it's the same kind of problem in several places I would say. I have provided a fix in #105

**Comment by agorararmard** [comment]
@thesourcerer8: This should be fixed since #109 was merged. However, I'll keep this issue open until the fix reaches `master`.

**Comment by agorararmard** [comment]
@thesourcerer8: Merged to master. I'm closing this issue as it's now resolved. Please, reopen if you find otherwise.
