### ISSUE TITLE
Enhance ./flow.tcl -interactive to pass argument to prep command and automatically load openlane package

### ISSUE THREAD

**Issue by 20Mhz** [efabless/openlane#11]
./flow -interactive -design spm -tag run1 -overwrite 

% require package openlane 0.9
% prep -design spm -tag run1 -overwrite

**Comment by agorararmard** [comment]
@20Mhz try rc3.

**Comment by agorararmard** [comment]
@20Mhz: I will assume the update in rc3 cover this issue. If you think it doesn't, please reopen.
