### ISSUE TITLE
CELL_PAD_EXCL missing in config.tcl

### ISSUE THREAD

**Issue by thesourcerer8** [efabless/openlane#111]
CELL_PAD_EXCL is missing from the dump of environment variables in config.tcl

**Comment by agorararmard** [comment]
@thesourcerer8: fixed in develop. I'll keep this open until it reaches master.

**Comment by agorararmard** [comment]
@thesourcerer8: Merged to master. I'm closing this issue as it's now resolved. Please, reopen if you find otherwise.
