### ISSUE TITLE
SELECT ROUTES

### ISSUE THREAD

**Issue by soorajkvl** [efabless/openlane#113]
The OpenLANE helps to include standard cells but not possible to include different LEF routing.

Example: Single die with PLL,USB,PICORV32A and routing between PLL and PICORV32A or USB and PICORV32A

Please help to know how is possible to route selective cells.

**Comment by agorararmard** [comment]
@soorajkvl: Can you elaborate more on your question? Do you mean you have 3 macros and you want to route signals between them? I'm not familiar with the term "LEF routing", so can you explain it to me or point me to some source?

**Comment by soorajkvl** [comment]
@agorararmard : Your guess is right. I have three macros (or Library Extension Formate .lef layout files) and need to do placement and route between them in OpenLANE.

How is that possible?

**Comment by agorararmard** [comment]
@soorajkvl: Check this directory https://github.com/efabless/openlane/tree/master/designs/manual_macro_placement_test

**Comment by agorararmard** [comment]
@soorajkvl: Did this answer your question?

**Comment by soorajkvl** [comment]
Yes, Thank you so much.
