### ISSUE TITLE
padframe genaration error

### ISSUE THREAD

**Issue by rsnkhatri3** [efabless/openlane#114]
I am keeping the padframe_folder in designs/my_design_folder, but below shown error occurs
<img width="547" alt="er1" src="https://user-images.githubusercontent.com/55553762/100817706-ab4f1400-3470-11eb-86a9-3025c29b3215.png">
<img width="548" alt="er2" src="https://user-images.githubusercontent.com/55553762/100817716-b013c800-3470-11eb-9720-c66f9efe758f.png">

**Comment by agorararmard** [comment]
@rsnkhatri3: We don't officially fully support automated chip integration. However, you can check this directory https://github.com/efabless/caravel/tree/develop-pruned/openlane/chip_io as an example of how to create a padframe. (Expect to do some manual edits in the layout when you go to the chip integration stage).

**Comment by rsnkhatri3** [comment]
While using the interactive script from above link, it asks for config.json file what to include in it.
