### ISSUE TITLE
-synth_explore flow.tcl switch errors with "No such file or directory" on develop branch

### ISSUE THREAD

**Issue by SweeperAA** [efabless/openlane#116]
When attempting to run ./flow.tcl -design <design_name> -synth_explore, the script errors out with:

********
[INFO]: Changing netlist from 0 to /openLANE_flow/designs/decred_block/runs/02-12_03-38/results/synthesis/decred_block.synthesis.v
[ERROR]: during executing: "sed -ie /defparam/d /openLANE_flow/designs/decred_block/runs/02-12_03-38/results/synthesis/decred_block.synthesis.v"
[ERROR]: Exit code: 1
[ERROR]: Last 10 lines:
sed: can't read /openLANE_flow/designs/decred_block/runs/02-12_03-38/results/synthesis/decred_block.synthesis.v: No such file or directory

[ERROR]: Please check sed  log file
[ERROR]: Dumping to /openLANE_flow/designs/decred_block/runs/02-12_03-38/error.log

    while executing
"try_catch sed -ie {/defparam/d} $::env(CURRENT_NETLIST)"
    (procedure "run_yosys" line 32)
    invoked from within
"run_yosys"
    (procedure "run_synth_exploration" line 5)
    invoked from within
"run_synth_exploration"
    invoked from within
"if { [info exists flags_map(-interactive)] || [info exists flags_map(-it)] } {
	puts_info "Running interactively"
	if { [info exists arg_values(-file)..."
    (file "./flow.tcl" line 168)
********

I looked in the results/synthesis directory and the following files were present:
- decred_block.synthesis_0.v
- decred_block.synthesis_1.v
- decred_block.synthesis_2.v
- decred_block.synthesis_3.v

**Comment by agorararmard** [comment]
@SweeperAA: Noted and fixed. Thanks!
