### ISSUE TITLE
Unble to do git 

### ISSUE THREAD

**Issue by mdzakirhussain** [efabless/openlane#12]
when I tried the following command 
git clone git@github.com:google/skywater-pdk.git

I am getting this 

Cloning into 'skywater-pdk'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by agorararmard** [comment]
@mdzakirhussain try using https for cloning: 
skywater-pdk:
https://github.com/google/skywater-pdk.git

open_pdks:
https://github.com/efabless/open_pdks.git

openlane:
https://github.com/efabless/openlane.git

**Comment by mdzakirhussain** [comment]
Thank you. Now it is working.
