### ISSUE TITLE
open_pdk make file issue 

### ISSUE THREAD

**Issue by mdzakirhussain** [efabless/openlane#13]
Makefile:42: *** 
 *********************************************************** 
 >>>>>>>>>>>>>>>>>> PDK_ROOT is not set <<<<<<<<<<<<<<<<<<<< 
 *********************************************************** 
 .  Stop.

**Comment by agorararmard** [comment]
@mdzakirhussain please check this: https://github.com/efabless/openlane/wiki/FAQs#why-am-i-unable-to-run-open_pdks
