### ISSUE TITLE
Indexing the logfiles

### ISSUE THREAD

**Issue by thesourcerer8** [efabless/openlane#157]
Please change the generated logfile filenames to a filename-scheme which orders the logfiles in a structured way (chronologically).
One thing to keep in mind is that some steps might be run several times during one flow, so they should not overwrite each other.
The goal is to make an analysis of all the logfiles easy.

**Comment by agorararmard** [comment]
@thesourcerer8: That is already the case in the develop branch. However, I'm going to keep this issue open until the changes reach master with rc7.

**Comment by agorararmard** [comment]
@thesourcerer8: This is now merged to master, so I'm closing this issue.
