### ISSUE TITLE
$(MAKE) variable in Makefile

### ISSUE THREAD

**Issue by d-m-bailey** [efabless/openlane#164]
The `$(MAKE)` variable is set at the start of the `Makefile` script.
On macos, this can be something like `/Library/Developer/CommandLineTools/usr/bin/make`

This `make` is not accessible from within docker, so all the `make` commands run in docker fail.

Specifically, `make build-pdk`

Suggest changing `$(MAKE)` to `make` in the `build-pdk` target.

**Comment by ax3ghazy** [comment]
Thanks. This https://github.com/efabless/openlane/commit/4203c39590191ca2befa2a0c1c02f96bed646785 should fix it.

**Comment by agorararmard** [comment]
@d-m-bailey: This is now merged to master, so I'm closing this issue.
