### ISSUE TITLE
About constraints

### ISSUE THREAD

**Issue by sultanbepari** [efabless/openlane#175]
Sir in  .sdc file what constraints can we modify except that time....can we modify area, power, clock frequency etc. Plz respond

**Comment by ax3ghazy** [comment]
Hello, you can have a look at the SDC section in https://www.intel.cn/content/dam/www/programmable/us/en/pdfs/literature/manual/mnl_sdctmq.pdf. There are also some helpful examples there.

**Comment by agorararmard** [comment]
@sultanbepari: I will assume the question is answered, please reopen if the issue still stands.
