### ISSUE TITLE
Iterations are keep going how long they will???

### ISSUE THREAD

**Issue by mdzakirhussain** [efabless/openlane#18]
PROC:  Start NESTEROV's Optimization
PROC:    Global Lagrangian Multiplier is Applied

ITER: 0
    HPWL=382.550232
    OVFL=0.725638
    HPWL=(159.536499, 223.013733)
    POTN=2.085887E+08
    PHIC=1.524986E-09
    GRAD=4.210845E-01
    NuBT=0
    CPU =0.000000

ITER: 1
    HPWL=376.941772
    OVFL=0.697518
    HPWL=(154.447601, 222.494186)
    POTN=1.924570E+08
    PHIC=1.601235E-09

**Comment by agorararmard** [comment]
@mdzakirhussain It takes a long time for large designs which could be considered to be a bug somehow in the placer. However, the iterations keep on going until OVFL is less than 0.1

**Comment by agorararmard** [comment]
@mdzakirhussain, could you please try rc3 and report if the issue still stands?

**Comment by agorararmard** [comment]
@mdzakirhussain, does this issue still stand or should I close it?

**Comment by mdzakirhussain** [comment]
do not close, the problem still there allow me till 10/october/2020.

**Comment by mdzakirhussain** [comment]
Now it is fine. Thank you.
