### ISSUE TITLE
How to perform custom pin-placement during Floorplanning?

### ISSUE THREAD

**Issue by nickson-jose** [efabless/openlane#20]
Hi,
I think the configurations for io pin placement during floorplanning is picked by openlane from /path/to/openlane/configuration/floorplan.tcl. However, I'm not sure of the steps to perform custom pin-placement during Floorplanning. 
For instance, for design, say picorv32a, if I want my 'resetn' pin to be precisely in the left, lower-half section; what all modifications do I need to do.

**Comment by ax3ghazy** [comment]
Hi @njose939,

This is currently not very possible. The only options you have for pin placement currently are random equidistant distribution of pins, or a placement that optimizes the HPWL (see the `FP_IO_MODE` configuration parameter). What you describe is a feature we wanted to implement for a while, so I will leave this open until it's available.

Thanks.

**Comment by agorararmard** [comment]
@nickson-jose: You can set `set ::env(FP_PIN_ORDER_CFG) $::env(DESIGN_DIR)/pin_order.cfg`and add a pin_order.cfg under your design directory like this one: https://github.com/efabless/openlane/blob/master/designs/spm/pin_order.cfg

**Comment by Haseeb-Baloch** [comment]
The example pin_order.cfg sets all 32 pins of the 'x' input to the north, is there anyway to divide these pins to 2 sides?

**Comment by agorararmard** [comment]
@Haseeb-Baloch: this will serve as a better example for you: https://github.com/efabless/caravel/blob/master/openlane/user_project_wrapper/pin_order.cfg

**Comment by Haseeb-Baloch** [comment]
thank you very much

**Comment by Haseeb-Baloch** [comment]
thank you

**Comment by Haseeb-Baloch** [comment]
Thank you @agorararmard this was exactly what I was looking for

**Comment by hanm2019** [comment]
Hi, I have a question about  `pin_order.cfg` file. It seem that It can custom the pins in which sides. 

If the pin_order.cfg is :

```
#N
x
y
z
```

Does it means that there are three pin in the north and the relative position of the three pins is decided, such as `x y z`? or  the `z x y` is also possible?
