### ISSUE TITLE
getting Segmentation fault (core dumped) while compiling ' magic -T sky130A lef read merged.lef def read picorv32a.floorplan.def'

### ISSUE THREAD

**Issue by shafnaskm** [efabless/openlane#266]

**Comment by agorararmard** [comment]
@shafnaskm: Wouldn't this question fit better in the magic repo? I don't know about loading the tech file directly with magic (regardless of having a `.tech` missing from your command and the absolute path to that tech file?). I think you better load the `.magicrc` file with `-rcfile` command:
```bash
magic -rcfile .magicrc
```
then inside magic, you'd write:
```tcl
lef read ...
def read ...
```
