### ISSUE TITLE
error during placement stage

### ISSUE THREAD

**Issue by praharshapm** [efabless/openlane#28]
Hi,
I am getting error on running run_placement. Replace is causing the issue. 
`[INFO] 80pCellArea = -nan 
[INFO] FillerInit: TotalFillerArea = 821.911865 
[INFO] FillerInit: NumFillerCells = -2147483648 
[INFO] FillerInit: FillerCellArea = -nan 
[INFO] FillerInit: FillerCellSize = (-nan, -nan) 
[ERROR]: during executing: "replace < /openLANE_flow/scripts//replace_gp.tcl |& tee >&@stdout /openLANE_flow/designs/AMUX2_3V_top/runs/19-08_07-19//logs/placement/replace.log"
 [ERROR]: Last 10 lines: child killed: segmentation violation`

After debugging, I understood that `rep place_cell_nesterov_place` is causing error which is present in replace_gp.tcl

Can someone please help?

**Comment by riking** [comment]
Input files are here: https://skywater-pdk.slack.com/archives/C016H8WJMBR/p1597847656281500?thread_ts=1597817669.264400&cid=C016H8WJMBR

**Comment by ax3ghazy** [comment]
I understand this has been resolved, right?

**Comment by praharshapm** [comment]
Yes. I actually increased the instance count by adding more circuitry to the design and thus the issue got resolved.
