### ISSUE TITLE
link to latest stable release are broken

### ISSUE THREAD

**Issue by mattvenn** [efabless/openlane#295]
**Describe the bug**

2 links at the top of the top level readme are both broken:
https://github.com/efabless/openlane/tree/release-0.x
https://github.com/efabless/openlane/tree/release-0.x

Then the instructions say clone rc 0.12.
links should match the instructions. 

I'm not sure if 0.12 is stable anyway, just had a report in openlane slack with very strange GDS output
https://skywater-pdk.slack.com/archives/C016H8WJMBR/p1618707155165900

**Comment by donn** [comment]
Fixed in `develop`. Thanks
