### ISSUE TITLE
Request for documentation or pointer to documentation

### ISSUE THREAD

**Issue by bhawandeepsingh** [efabless/openlane#299]
**Is your feature request related to a problem? Please describe.**
I need to floorplan and place multiple projects - riscv, memories, uart etc rather than combining them into a single heirarchical project. My first approach was to synthesize them as separate projects and proceed. Now I remember openlane expects projects to follow a given directory structure and possibly all relevant files to be present in a common location for a particular stage. Hence, not sure how to go ahead with it.

**Describe the solution you'd like**
Can you provide a link to instructions for doing this ? Thanks

**Describe alternatives you've considered**

**Additional context**

**Comment by mguthaus** [comment]
I think you want this:
https://openlane.readthedocs.io/en/develop/docs/source/hardening_macros.html

And if you click the link in that section it leads to this:
https://openlane.readthedocs.io/en/develop/docs/source/chip_integration.html
