### ISSUE TITLE
openLANE/efabless 

### ISSUE THREAD

**Issue by chandni0760** [efabless/openlane#31]
Hello I am Unable to clone the skywater-pdk  using the following command;
**git clone https://github.com/google/skywater-pdk**

**Comment by PaulSchulz** [comment]
Work for me. What error do you get?

**Comment by PaulSchulz** [comment]
What type of system are you using?

**Comment by chandni0760** [comment]
Hi I am using Linux OS

**Comment by PaulSchulz** [comment]
I'm using Ubuntu 20.04  (linux) and the command worked for me. What error do you get?

**Comment by PaulSchulz** [comment]
You should see something like..

paul@silver:~/tmp$ git clone https://github.com/google/skywater-pdk
Cloning into 'skywater-pdk'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 903 (delta 11), reused 15 (delta 6), pack-reused 877
Receiving objects: 100% (903/903), 2.05 MiB | 1.62 MiB/s, done.
Resolving deltas: 100% (401/401), done.

**Comment by chandni0760** [comment]
Hello Sir,

Can you tell me how much time does it take to install /clone the
skywater-pdk and nothing of this sort is coming as you have shown .
I had kept the run yesterday night and still its not done so asked for the
help
Will share you the screenshot of the same

PFA

**Comment by PaulSchulz** [comment]
Command is type in at the terminal prompt.
- On my internet connection it takes less than 1 minute.

Can you 'ping' 'google.com' ?

**Comment by chandni0760** [comment]
Sure let me try

Thanks

**Comment by agorararmard** [comment]
@chandni0760 Does the issue still stand?

**Comment by chandni0760** [comment]
Hi,

Yes May be I have issue in my Laptop itself can't install it on my laptop I
have also pinged Google.com and it works but issue lies in my system hence
I have already confronted the query to My IT Executive

Thanks a lot for the support!!

**Comment by agorararmard** [comment]
@chandni0760, does the issue still stand?

**Comment by agorararmard** [comment]
@chandni0760: I will assume this is resolved and close the issue. Please, reopen if it still stands.
