### ISSUE TITLE
Error during execution of detailed placement 

### ISSUE THREAD

**Issue by Geetima2021** [efabless/openlane#321]
![error_DP_openDP](https://user-images.githubusercontent.com/63381455/116982541-8a704080-ace6-11eb-9010-eabd0e0ddae4.png)
I have been using the run_placement command but I am facing the above issue. I had simultaneously run the run_placement command a no, of times. Each time Warning: Site check failed (133) increase and also the no. of psn_inst_psn_buff_1301
increases but the error remains. I had also set the FP_CORE_UTIL to default 50, PL_TARGET_DENSITY to 0.55 and CELL_PAD 4. Kindly assist me in resolving the above issue as I am not being able to figure out anything.

**Comment by guris12** [comment]
could you check log file ?

**Comment by Geetima2021** [comment]
Yes I checked...This is what the error.log file shows.
during executing: "openroad -exit /openLANE_flow/scripts/openroad/or_opendp.tcl |& tee >&@stdout /openLANE_flow/designs/picorv32a/runs/PD_03May/logs/placement/opendp.log"
Last 10 lines:
child process exited abnormally

**Comment by Manarabdelaty** [comment]
@Geetima2021 Can you post the `opendp.log` file ? It should be under `logs/placement`

**Comment by Geetima2021** [comment]
![error_DP_openDP](https://user-images.githubusercontent.com/63381455/117251248-05119b00-ae62-11eb-905b-a73fe86a485e.png)

**Comment by Geetima2021** [comment]
I exactly don't know what happened but it is most probably working and not showing any error now.
