### ISSUE TITLE
default 'LIB_MIN' and 'LIB_MAX' settings in openlane

### ISSUE THREAD

**Issue by nickson-jose** [efabless/openlane#37]
The README.md for openlane defines following .libs as defaults for min and max analysis..

| `LIB_MIN` | Library used for min delay calculation during STA. <br> (Default:`./pdks/ef-skywater-s8/EFS8A/libs.ref/liberty/efs8hd/efs8hd_ss_1.60v_100C.lib`) |
| `LIB_MAX`  | Library used for max delay calculation during STA. <br> (Default:`./pdks/ef-skywater-s8/EFS8A/libs.ref/liberty/efs8hd/efs8hd_ff_1.95v_-40C.lib`) |

Shouldn't it be the other way round, i.e., 
'ss' .lib as `LIB_MAX` and 'ff' .lib as `LIB_MIN` ?

**Comment by agorararmard** [comment]
Yes, this an issue was discovered a while ago and fixed it in the `develop` branch, but it hasn't made its way to master yet. They should be switched to:
```
LIB_MAX to sky130_fd_sc_hd__ss_100C_1v60.lib
LIB_MIN to sky130_fd_sc_hd__ff_n40C_1v95.lib
```
These reside under `$PDK_ROOT/sky130A/libs.tech/openlane/sky130_fd_sc_hd/config.tcl`.

Also, the base.sdc should be modified to [this](https://github.com/efabless/openlane/blob/develop/scripts/base.sdc).
