### ISSUE TITLE
where do see the STA files while executing openlane

### ISSUE THREAD

**Issue by anandr2998** [efabless/openlane#49]

**Comment by tgingold** [comment]
The reports are in `designs/NAME/runs/TAG/reports`, where NAME is your design name and TAG the run tag (default is date and time).

The STA reports are in the `synthesis` subdirectory of `reports`.  The files are `opensta.*` for post synthesis reports, `opensta_post_openphysyn.*` after openphysyn and `opensta_spef*` after routing.
