### ISSUE TITLE
`make test` failure on rc4

### ISSUE THREAD

**Issue by jeras** [efabless/openlane#82]
I First tried openlane rc3 last week, I was able to install all dependencies and to add myself to the docker group.
I was able to run `make test` without issues. This is on Ubuntu 20.04.

Today I tried `rc4` twice, the second time with a thorough cleanup (not sure about docker).
`make test` ends with the next message:
```
[INFO]: /openLANE_flow/designs/spm/runs/openlane_test/results/magic/spm.spice against /openLANE_flow/designs/spm/runs/openlane_test/results/lvs/spm.lvs.powered.v
[INFO]: Running Antenna Checks...
[INFO]: Running OpenROAD Antenna Rule Checker...
[INFO]: Generating Final Summary Report...
[SUCCESS]: Flow Completed Without Fatal Errors.
/bin/sh: 1: [[: not found
Basic test failed
```

**Comment by riking** [comment]
`/bin/sh: 1: [[: not found`

A script using bashisms is missing the `#!/bin/bash`.

**Comment by ax3ghazy** [comment]
@jeras, @riking: Thanks! This is now fixed in develop.

**Comment by agorararmard** [comment]
I'm re-opening this until the fix reaches master.
