### ISSUE TITLE
Please document MERGE_LEF

### ISSUE THREAD

**Issue by thesourcerer8** [efabless/openlane#98]

**Comment by agorararmard** [comment]
@thesourcerer8: So, until I add this documentation (soon).
`merged_unpadded.lef`: the technology LEF for the used `STD_CELL_LIBRARY` merged with the LEF file for all the cells. This is pointed to with `MERGED_LEF_UNPADDED`.
`merged.lef`: `merged_unpadded.lef` but with cell padding. This is controlled by `CELL_PAD`. This is pointed to with `MERGED_LEF`.

**Comment by agorararmard** [comment]
@thesourcerer8: merged to master.
